import type { Restaurant } from './types'

/** Bundled local photos in `src/assets` (works with Vite `base`). */
const restaurantPhoto = {
  gordonAvenue: new URL('./assets/gordon-avenue-market.jpg', import.meta.url).href,
  memorialUnion: new URL('./assets/memorial-union-terrace.png', import.meta.url).href,
  iansPizza: new URL("./assets/ian's-pizza-on-state.jpg", import.meta.url).href,
  derRathskeller: new URL('./assets/der-rathskeller.jpg', import.meta.url).href,
  stateStreetBrats: new URL('./assets/State-Street-Brats-Exterior.jpg', import.meta.url).href,
  fourLakes: new URL('./assets/four-lakes-market.jpg', import.meta.url).href,
  dottyDumplings: new URL("./assets/Dotty-Dumpling's-Dowry.webp", import.meta.url).href,
  tavernakaya: new URL('./assets/Tavernakaya.jpeg', import.meta.url).href,
  letoile: new URL("./assets/L'Etoile.jpg", import.meta.url).href,
  mickies: new URL('./assets/Mickies-Dairy-Bar.webp', import.meta.url).href,
  graze: new URL('./assets/Graze.jpg', import.meta.url).href,
  glorias: new URL("./assets/gloria's-mexican-restaurant.jpg", import.meta.url).href,
  parthenon: new URL('./assets/Parthenon-Gyros.avif', import.meta.url).href,
  swad: new URL('./assets/Swad-Indian-Restaurant.jpg', import.meta.url).href,
  sogaMochi: new URL('./assets/Soga-Mochi-Donut.webp', import.meta.url).href,
  salvatores: new URL("./assets/Salvatore's-Tomato-Pies.jpg", import.meta.url).href,
  colectivo: new URL('./assets/Colectivo.webp', import.meta.url).href,
  everly: new URL('./assets/Everly.avif', import.meta.url).href,
  oldFashioned: new URL('./assets/the-old-fashioned.jpg', import.meta.url).href,
  laoLaanXang: new URL('./assets/Lao-Laan-Xang.jpg', import.meta.url).href,
} as const

export const UW_COLORS = {
  red: '#c5050c',
  darkRed: '#9b0000',
  white: '#ffffff',
  gray: '#f7f7f7',
  darkGray: '#282828',
}

/**
 * Broad cuisine filters for the meal picker (keep each restaurant’s `foodTypes` subset of this list).
 * Fewer options than fine-grained cuisine labels so users can choose quickly.
 */
export const FOOD_GENRES = [
  'American & Pub',
  'Asian',
  'Breakfast & Coffee',
  'Fine Dining',
  'Late Night',
  'Mediterranean',
  'Mexican & Latin',
  'Pizza & Italian',
  'Vegetarian-friendly',
] as const

export const MOCK_RESTAURANTS: Restaurant[] = [
  {
    id: '1',
    name: 'Gordon Avenue Market',
    description:
      'A popular campus dining hall offering a variety of stations from stir-fry to classic comfort food.',
    foodTypes: ['American & Pub', 'Asian', 'Pizza & Italian'],
    budget: 1,
    distance: 0.4,
    rating: 4.2,
    imageUrl: restaurantPhoto.gordonAvenue,
    address: '770 W Dayton St, Madison, WI 53706',
    hours: '7:00 AM - 9:00 PM',
    phone: '(608) 262-2231',
    website: 'https://www.housing.wisc.edu/dining/locations/gordon/',
  },
  {
    id: '2',
    name: 'Memorial Union Terrace',
    description: 'The iconic lakeside spot for brats, beer, and beautiful sunsets.',
    foodTypes: ['American & Pub'],
    budget: 2,
    distance: 0.2,
    rating: 4.8,
    imageUrl: restaurantPhoto.memorialUnion,
    address: '800 Langdon St, Madison, WI 53706',
    hours: '11:00 AM - 11:00 PM',
    phone: '(608) 265-3000',
    website: 'https://union.wisc.edu/visit/terrace-at-the-memorial-union',
  },
  {
    id: '3',
    name: "Ian's Pizza on State",
    description: "Famous for Mac n' Cheese pizza and late-night slices.",
    foodTypes: ['Pizza & Italian', 'Late Night'],
    budget: 1,
    distance: 0.5,
    rating: 4.6,
    imageUrl: restaurantPhoto.iansPizza,
    address: '100 State St, Madison, WI 53703',
    hours: '11:00 AM - 3:00 AM',
    phone: '(608) 257-9248',
    website: 'https://ianspizza.com/',
  },
  {
    id: '4',
    name: 'Der Rathskeller',
    description: 'A German-style beer hall located in Memorial Union.',
    foodTypes: ['American & Pub', 'Breakfast & Coffee'],
    budget: 2,
    distance: 0.2,
    rating: 4.4,
    imageUrl: restaurantPhoto.derRathskeller,
    address: '800 Langdon St, Madison, WI 53706',
    hours: '7:30 AM - 10:00 PM',
    phone: '(608) 262-2263',
    website: 'https://union.wisc.edu/dine/find-food-and-drink/der-rathskeller',
  },
  {
    id: '5',
    name: 'State Street Brats',
    description: 'The legendary Madison sports bar known for red and white brats.',
    foodTypes: ['American & Pub'],
    budget: 2,
    distance: 0.6,
    rating: 4.3,
    imageUrl: restaurantPhoto.stateStreetBrats,
    address: '603 State St, Madison, WI 53703',
    hours: '11:00 AM - 2:00 AM',
    phone: '(608) 255-5544',
    website: 'https://statestreetbrats.com/',
  },
  {
    id: '6',
    name: 'Four Lakes Market',
    description: 'Dining hall in Dejope Residence Hall with great views of Lake Mendota.',
    foodTypes: ['American & Pub', 'Vegetarian-friendly'],
    budget: 1,
    distance: 1.2,
    rating: 4.1,
    imageUrl: restaurantPhoto.fourLakes,
    address: '640 Elm Dr, Madison, WI 53706',
    hours: '7:00 AM - 8:00 PM',
    phone: '(608) 262-1322',
    website: 'https://www.housing.wisc.edu/dining/locations/four-lakes/',
  },
  {
    id: '7',
    name: "Dotty Dumpling's Dowry",
    description: 'Home of the world famous burgers and delicious homemade sauces.',
    foodTypes: ['American & Pub'],
    budget: 2,
    distance: 0.8,
    rating: 4.7,
    imageUrl: restaurantPhoto.dottyDumplings,
    address: '317 N Frances St, Madison, WI 53703',
    hours: '11:00 AM - 10:00 PM',
    phone: '(608) 259-0000',
    website: 'https://dottydumplingsdowry.com/',
  },
  {
    id: '8',
    name: 'Tavernakaya',
    description: 'Modern Japanese tavern serving sushi, ramen, and creative cocktails.',
    foodTypes: ['Asian'],
    budget: 3,
    distance: 0.9,
    rating: 4.5,
    imageUrl: restaurantPhoto.tavernakaya,
    address: '27 E Main St, Madison, WI 53703',
    hours: '11:00 AM - 11:00 PM',
    phone: '(608) 555-0123',
    website: 'https://tavernakaya.com/',
  },
  {
    id: '9',
    name: "L'Etoile",
    description: 'Fine dining featuring locally sourced ingredients and an elegant atmosphere.',
    foodTypes: ['Fine Dining'],
    budget: 4,
    distance: 1.0,
    rating: 4.9,
    imageUrl: restaurantPhoto.letoile,
    address: '1 S Pinckney St, Madison, WI 53703',
    hours: '5:00 PM - 10:00 PM',
    phone: '(608) 251-0500',
    website: 'https://letoile-restaurant.com/',
  },
  {
    id: '10',
    name: 'Mickies Dairy Bar',
    description: 'Classic 1950s-style diner famous for huge breakfasts and milkshakes.',
    foodTypes: ['Breakfast & Coffee'],
    budget: 1,
    distance: 0.7,
    rating: 4.6,
    imageUrl: restaurantPhoto.mickies,
    address: '1511 Monroe St, Madison, WI 53711',
    hours: '6:00 AM - 2:00 PM',
    phone: '(608) 256-9441',
    website: 'https://mickiesdairybar.com/',
  },
  {
    id: '11',
    name: 'Graze',
    description: 'Seasonal Midwestern plates and cheese boards in a bright Capitol Square dining room.',
    foodTypes: ['Fine Dining'],
    budget: 3,
    distance: 0.5,
    rating: 4.5,
    imageUrl: restaurantPhoto.graze,
    address: '1 S Pinckney St #107, Madison, WI 53703',
    hours: '11:00 AM - 9:00 PM',
    phone: '(608) 251-5300',
    website: 'https://www.grazemadison.com/',
  },
  {
    id: '12',
    name: 'Gloria\'s Mexican Restaurant',
    description: 'One of Madison\'s most authentic Mexican restaurants in Madison',
    foodTypes: ['Mexican & Latin', 'American & Pub'],
    budget: 2,
    distance: 0.55,
    rating: 4.4,
    imageUrl: restaurantPhoto.glorias,
    address: '744 Williamson St, Madison, WI 53703',
    hours: '11:00 AM - 10:00 PM',
    phone: '(608) 256-3172',
    website: 'https://gloriasmexican.com/',
  },
  {
    id: '13',
    name: 'Parthenon Gyros',
    description: 'Quick-service Greek classics and late-night gyros near campus.',
    foodTypes: ['Mediterranean', 'Late Night'],
    budget: 1,
    distance: 0.45,
    rating: 4.3,
    imageUrl: restaurantPhoto.parthenon,
    address: '316 State St, Madison, WI 53703',
    hours: '10:30 AM - 3:00 AM',
    phone: '(608) 251-6765',
    website: 'https://parthenongyros.com/',
  },
  {
    id: '14',
    name: 'Swad Indian Restaurant',
    description: 'Buffet lunch and a la carte curries with vegetarian-friendly options.',
    foodTypes: ['Asian', 'Vegetarian-friendly'],
    budget: 2,
    distance: 1.1,
    rating: 4.4,
    imageUrl: restaurantPhoto.swad,
    address: '1901 W Beltline Hwy, Madison, WI 53713',
    hours: '11:00 AM - 9:30 PM',
    phone: '(608) 441-1414',
    website: 'https://www.swadmonona.com/',
  },
  {
    id: '15',
    name: 'Soga Mochi Donut',
    description: 'Crispy mochi donuts and Korean-inspired drinks steps from Library Mall.',
    foodTypes: ['Asian', 'Breakfast & Coffee'],
    budget: 1,
    distance: 0.35,
    rating: 4.6,
    imageUrl: restaurantPhoto.sogaMochi,
    address: '333 W Washington Ave, Madison, WI 53703',
    hours: '10:00 AM - 8:00 PM',
    phone: '(608) 555-0198',
    website: 'https://sogamochidonut.com/',
  },
  {
    id: '16',
    name: 'Salvatore\'s Tomato Pies',
    description: 'Wood-fired pies, seasonal salads, and a neighborhood vibe on Monona Drive.',
    foodTypes: ['Pizza & Italian', 'Vegetarian-friendly'],
    budget: 2,
    distance: 1.0,
    rating: 4.7,
    imageUrl: restaurantPhoto.salvatores,
    address: '912 E Johnson St, Madison, WI 53703',
    hours: '11:00 AM - 9:00 PM',
    phone: '(608) 251-6373',
    website: 'https://www.salvatorestomatopies.com/',
  },
  {
    id: '17',
    name: 'Colectivo',
    description: 'Local roaster cafe with sandwiches, pastries, and Capitol views.',
    foodTypes: ['Breakfast & Coffee'],
    budget: 1,
    distance: 0.6,
    rating: 4.5,
    imageUrl: restaurantPhoto.colectivo,
    address: '25 S Pinckney St, Madison, WI 53703',
    hours: '6:30 AM - 6:00 PM',
    phone: '(608) 709-1919',
    website: 'https://colectivocoffee.com/',
  },
  {
    id: '18',
    name: 'Everly',
    description: 'bright, eclectic American restaurant on Monroe Street in Madison, WI, known for veggie-forward dishes, craft cocktails, and weekend brunch.',
    foodTypes: ['Vegetarian-friendly', 'American & Pub'],
    budget: 2,
    distance: 0.85,
    rating: 4.2,
    imageUrl: restaurantPhoto.everly,
    address: '10 S Bedford St, Madison, WI 53703',
    hours: '11:00 AM - 9:00 PM',
    phone: '(608) 251-9133',
    website: 'https://www.everlymadison.com/interior-gallery/',
  },
  {
    id: '19',
    name: 'The Old Fashioned',
    description: 'Wisconsin supper club classics, cheese curds, and a deep old-fashioneds list.',
    foodTypes: ['American & Pub'],
    budget: 2,
    distance: 0.25,
    rating: 4.6,
    imageUrl: restaurantPhoto.oldFashioned,
    address: '1 N Pinckney St, Madison, WI 53703',
    hours: '11:00 AM - 10:00 PM',
    phone: '(608) 310-4545',
    website: 'https://theoldfashioned.com/',
  },
  {
    id: '20',
    name: 'Lao Laan-Xang',
    description: 'Beloved Lao and Thai curries, papaya salad, and coconut soups.',
    foodTypes: ['Asian', 'Vegetarian-friendly'],
    budget: 2,
    distance: 1.4,
    rating: 4.5,
    imageUrl: restaurantPhoto.laoLaanXang,
    address: '1140 Williamson St, Madison, WI 53703',
    hours: '11:00 AM - 9:00 PM',
    phone: '(608) 255-8778',
    website: 'https://www.laolaan-xang.com/',
  },
]
