import type { Restaurant } from './types'

export const UW_COLORS = {
  red: '#c5050c',
  darkRed: '#9b0000',
  white: '#ffffff',
  gray: '#f7f7f7',
  darkGray: '#282828',
}

/** Cuisine tags used in filters and on restaurant cards; keep `foodTypes` aligned with this list. */
export const FOOD_GENRES = [
  'American',
  'Breakfast',
  'Burgers',
  'Coffee',
  'Diner',
  'Fine Dining',
  'French',
  'German',
  'Global',
  'Ice Cream',
  'Indian',
  'Italian',
  'Japanese',
  'Korean',
  'Late Night',
  'Latin',
  'Mediterranean',
  'Mexican',
  'Pizza',
  'Pub Food',
  'Ramen',
  'Salad Bar',
  'Sandwich',
  'Sports Bar',
  'Stir-fry',
  'Sushi',
  'Thai',
  'Vegetarian',
] as const

export const MOCK_RESTAURANTS: Restaurant[] = [
  {
    id: '1',
    name: 'Gordon Avenue Market',
    description:
      'A popular campus dining hall offering a variety of stations from stir-fry to classic comfort food.',
    foodTypes: ['American', 'Stir-fry', 'Pizza'],
    budget: 1,
    distance: 0.4,
    rating: 4.2,
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/6/65/Gordon_Dining_and_Event_Center_election_day_2022_%28IMG_7430%29.jpg',
    address: '770 W Dayton St, Madison, WI 53706',
    hours: '7:00 AM - 9:00 PM',
    phone: '(608) 262-2231',
    website: 'https://www.housing.wisc.edu/dining/gordon-avenue-market/',
  },
  {
    id: '2',
    name: 'Memorial Union Terrace',
    description: 'The iconic lakeside spot for brats, beer, and beautiful sunsets.',
    foodTypes: ['American', 'Pub Food', 'Ice Cream'],
    budget: 2,
    distance: 0.2,
    rating: 4.8,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/bc/Memorial_Union_Terrace_2024.jpg',
    address: '800 Langdon St, Madison, WI 53706',
    hours: '11:00 AM - 11:00 PM',
    phone: '(608) 265-3000',
    website: 'https://union.wisc.edu/visit/terrace/',
  },
  {
    id: '3',
    name: "Ian's Pizza on State",
    description: "Famous for Mac n' Cheese pizza and late-night slices.",
    foodTypes: ['Pizza', 'Late Night'],
    budget: 1,
    distance: 0.5,
    rating: 4.6,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/9a/Ian%27s_Pizza_-_panoramio.jpg',
    address: '100 State St, Madison, WI 53703',
    hours: '11:00 AM - 3:00 AM',
    phone: '(608) 257-9248',
    website: 'https://ianspizza.com/',
  },
  {
    id: '4',
    name: 'Der Rathskeller',
    description: 'A German-style beer hall located in Memorial Union.',
    foodTypes: ['German', 'American', 'Breakfast'],
    budget: 2,
    distance: 0.2,
    rating: 4.4,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/bd/Der_Rathekeller_at_UW-Madison.jpg',
    address: '800 Langdon St, Madison, WI 53706',
    hours: '7:30 AM - 10:00 PM',
    phone: '(608) 262-2263',
    website: 'https://union.wisc.edu/visit/der-rathskeller/',
  },
  {
    id: '5',
    name: 'State Street Brats',
    description: 'The legendary Madison sports bar known for red and white brats.',
    foodTypes: ['American', 'Pub Food', 'Sports Bar'],
    budget: 2,
    distance: 0.6,
    rating: 4.3,
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/3/3f/Conklin_Block%2C_State_Street_and_Henry_Street%2C_Madison%2C_WI_%2852734132594%29.jpg',
    address: '603 State St, Madison, WI 53703',
    hours: '11:00 AM - 2:00 AM',
    phone: '(608) 255-5544',
    website: 'https://statestreetbrats.com/',
  },
  {
    id: '6',
    name: 'Four Lakes Market',
    description: 'Dining hall in Dejope Residence Hall with great views of Lake Mendota.',
    foodTypes: ['American', 'Global', 'Salad Bar'],
    budget: 1,
    distance: 1.2,
    rating: 4.1,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b7/Dejope_Hall-front.JPG',
    address: '640 Elm Dr, Madison, WI 53706',
    hours: '7:00 AM - 8:00 PM',
    phone: '(608) 262-1322',
    website: 'https://www.housing.wisc.edu/dining/four-lakes-market/',
  },
  {
    id: '7',
    name: "Dotty Dumpling's Dowry",
    description: 'Home of the world famous burgers and delicious homemade sauces.',
    foodTypes: ['Burgers', 'American'],
    budget: 2,
    distance: 0.8,
    rating: 4.7,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/da/Monty%27s_Blue_Plate_Diner_-_panoramio.jpg',
    address: '317 N Frances St, Madison, WI 53703',
    hours: '11:00 AM - 10:00 PM',
    phone: '(608) 259-0000',
    website: 'https://dottydumplingsdowry.com/',
  },
  {
    id: '8',
    name: 'Tavernakaya',
    description: 'Modern Japanese tavern serving sushi, ramen, and creative cocktails.',
    foodTypes: ['Japanese', 'Sushi', 'Ramen'],
    budget: 3,
    distance: 0.9,
    rating: 4.5,
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/6/64/Journey_Sushi_%5E_Seafood_Buffet_-_panoramio.jpg',
    address: '27 E Main St, Madison, WI 53703',
    hours: '11:00 AM - 11:00 PM',
    phone: '(608) 555-0123',
    website: 'https://tavernakaya.com/',
  },
  {
    id: '9',
    name: "L'Etoile",
    description: 'Fine dining featuring locally sourced ingredients and an elegant atmosphere.',
    foodTypes: ['French', 'Fine Dining'],
    budget: 4,
    distance: 1.0,
    rating: 4.9,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/ee/Belmont_Hotel_%28Madison%29.jpg',
    address: '1 S Pinckney St, Madison, WI 53703',
    hours: '5:00 PM - 10:00 PM',
    phone: '(608) 251-0500',
    website: 'https://letoile-restaurant.com/',
  },
  {
    id: '10',
    name: 'Mickies Dairy Bar',
    description: 'Classic 1950s-style diner famous for huge breakfasts and milkshakes.',
    foodTypes: ['Diner', 'Breakfast'],
    budget: 1,
    distance: 0.7,
    rating: 4.6,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/a5/Mickies_Dairy_Bar_%28Madison%2C_WI%29.jpg',
    address: '1511 Monroe St, Madison, WI 53711',
    hours: '6:00 AM - 2:00 PM',
    phone: '(608) 256-9441',
    website: 'https://mickiesdairybar.com/',
  },
  {
    id: '11',
    name: 'Graze',
    description: 'Seasonal Midwestern plates and cheese boards in a bright Capitol Square dining room.',
    foodTypes: ['American', 'Fine Dining'],
    budget: 3,
    distance: 0.5,
    rating: 4.5,
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/2/26/10_East_Doty%2C_Doty_Street_and_Pinckney_Street%2C_Madison%2C_WI_%2852745541603%29.jpg',
    address: '1 S Pinckney St #107, Madison, WI 53703',
    hours: '11:00 AM - 9:00 PM',
    phone: '(608) 251-5300',
    website: 'https://www.grazemadison.com/',
  },
  {
    id: '12',
    name: 'Eldorado Grill',
    description: 'Southwestern flavors, margaritas, and a lively State Street patio.',
    foodTypes: ['Mexican', 'Latin', 'Pub Food'],
    budget: 2,
    distance: 0.55,
    rating: 4.4,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e8/Diego%27s_Mexican_Bistro_-_panoramio.jpg',
    address: '744 Williamson St, Madison, WI 53703',
    hours: '11:00 AM - 10:00 PM',
    phone: '(608) 256-3172',
    website: 'https://eldorado-grill.com/',
  },
  {
    id: '13',
    name: 'Parthenon Gyros',
    description: 'Quick-service Greek classics and late-night gyros near campus.',
    foodTypes: ['Mediterranean', 'Late Night'],
    budget: 1,
    distance: 0.45,
    rating: 4.3,
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/e/e9/Oliva_Italian_Mediterranean_Cuisine_-_panoramio.jpg',
    address: '316 State St, Madison, WI 53703',
    hours: '10:30 AM - 3:00 AM',
    phone: '(608) 251-6765',
    website: 'https://parthenongyros.com/',
  },
  {
    id: '14',
    name: 'Swad Indian Restaurant',
    description: 'Buffet lunch and a la carte curries with vegetarian-friendly options.',
    foodTypes: ['Indian', 'Vegetarian'],
    budget: 2,
    distance: 1.1,
    rating: 4.4,
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/d/df/Fast_biryani_Gourmet_Indian_Cusine_-_panoramio.jpg',
    address: '1901 W Beltline Hwy, Madison, WI 53713',
    hours: '11:00 AM - 9:30 PM',
    phone: '(608) 441-1414',
    website: 'https://www.swadofindia.com/',
  },
  {
    id: '15',
    name: 'Soga Mochi Donut',
    description: 'Crispy mochi donuts and Korean-inspired drinks steps from Library Mall.',
    foodTypes: ['Korean', 'Coffee'],
    budget: 1,
    distance: 0.35,
    rating: 4.6,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/7a/EVP_Coffee_-_panoramio.jpg',
    address: '333 W Washington Ave, Madison, WI 53703',
    hours: '10:00 AM - 8:00 PM',
    phone: '(608) 555-0198',
    website: 'https://www.sogamochidonut.com/',
  },
  {
    id: '16',
    name: 'Salvatore\'s Tomato Pies',
    description: 'Wood-fired pies, seasonal salads, and a neighborhood vibe on Monona Drive.',
    foodTypes: ['Italian', 'Pizza', 'Salad Bar'],
    budget: 2,
    distance: 1.0,
    rating: 4.7,
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/8/83/Roman_Candle_Pizzeria_-_panoramio.jpg',
    address: '912 E Johnson St, Madison, WI 53703',
    hours: '11:00 AM - 9:00 PM',
    phone: '(608) 251-6373',
    website: 'https://www.salvatorestomatopies.com/',
  },
  {
    id: '17',
    name: 'Colectivo on the Square',
    description: 'Local roaster cafe with sandwiches, pastries, and Capitol views.',
    foodTypes: ['Coffee', 'Sandwich', 'Breakfast'],
    budget: 1,
    distance: 0.6,
    rating: 4.5,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/ed/Espresso_Royale_-_panoramio.jpg',
    address: '25 S Pinckney St, Madison, WI 53703',
    hours: '6:30 AM - 6:00 PM',
    phone: '(608) 709-1919',
    website: 'https://colectivocoffee.com/',
  },
  {
    id: '18',
    name: 'Evergreen Restaurant',
    description: 'Vegetarian and vegan Chinese dishes with generous tofu and mock-meat options.',
    foodTypes: ['Vegetarian', 'Stir-fry'],
    budget: 2,
    distance: 0.85,
    rating: 4.2,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/51/Stir_Fry_88_-_panoramio.jpg',
    address: '10 S Bedford St, Madison, WI 53703',
    hours: '11:00 AM - 9:00 PM',
    phone: '(608) 251-9133',
    website: 'https://www.evergreenmadison.com/',
  },
  {
    id: '19',
    name: 'The Old Fashioned',
    description: 'Wisconsin supper club classics, cheese curds, and a deep old-fashioneds list.',
    foodTypes: ['American', 'Pub Food'],
    budget: 2,
    distance: 0.25,
    rating: 4.6,
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/c/c5/Capitol_Theater%2C_State_Street%2C_Madison%2C_WI_%2852733355527%29.jpg',
    address: '1 N Pinckney St, Madison, WI 53703',
    hours: '11:00 AM - 10:00 PM',
    phone: '(608) 310-4545',
    website: 'https://theoldfashioned.com/',
  },
  {
    id: '20',
    name: 'Lao Laan-Xang',
    description: 'Beloved Lao and Thai curries, papaya salad, and coconut soups.',
    foodTypes: ['Thai', 'Vegetarian'],
    budget: 2,
    distance: 1.4,
    rating: 4.5,
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/d/d7/Lao_Laan_Xang_Restaurant_-_panoramio.jpg',
    address: '1140 Williamson St, Madison, WI 53703',
    hours: '11:00 AM - 9:00 PM',
    phone: '(608) 255-8778',
    website: 'https://www.laolaanxang.com/',
  },
]
