import type { Restaurant } from './types'

export const UW_COLORS = {
  red: '#c5050c',
  darkRed: '#9b0000',
  white: '#ffffff',
  gray: '#f7f7f7',
  darkGray: '#282828',
}

export const MOCK_RESTAURANTS: Restaurant[] = [
  {
    id: '1',
    name: 'Gordon Avenue Market',
    description:
      'A popular campus dining hall offering a variety of stations from stir-fry to classic comfort food.',
    foodTypes: ['American', 'Stir-fry', 'Pizza'],
    budget: 1,
    distance: 0.4,
    rating: 4.2,
    imageUrl: 'https://picsum.photos/seed/gordon/800/600',
    address: '770 W Dayton St, Madison, WI 53706',
    hours: '7:00 AM - 9:00 PM',
    phone: '(608) 262-2231',
    website: 'https://www.housing.wisc.edu/dining/gordon-avenue-market/',
  },
  {
    id: '2',
    name: 'Memorial Union Terrace',
    description: 'The iconic lakeside spot for brats, beer, and beautiful sunsets.',
    foodTypes: ['American', 'Pub Food', 'Ice Cream'],
    budget: 2,
    distance: 0.2,
    rating: 4.8,
    imageUrl: 'https://picsum.photos/seed/terrace/800/600',
    address: '800 Langdon St, Madison, WI 53706',
    hours: '11:00 AM - 11:00 PM',
    phone: '(608) 265-3000',
    website: 'https://union.wisc.edu/visit/terrace/',
  },
  {
    id: '3',
    name: "Ian's Pizza on State",
    description: "Famous for Mac n' Cheese pizza and late-night slices.",
    foodTypes: ['Pizza', 'Late Night'],
    budget: 1,
    distance: 0.5,
    rating: 4.6,
    imageUrl: 'https://picsum.photos/seed/ians/800/600',
    address: '100 State St, Madison, WI 53703',
    hours: '11:00 AM - 3:00 AM',
    phone: '(608) 257-9248',
    website: 'https://ianspizza.com/',
  },
  {
    id: '4',
    name: 'Der Rathskeller',
    description: 'A German-style beer hall located in Memorial Union.',
    foodTypes: ['German', 'American', 'Breakfast'],
    budget: 2,
    distance: 0.2,
    rating: 4.4,
    imageUrl: 'https://picsum.photos/seed/rath/800/600',
    address: '800 Langdon St, Madison, WI 53706',
    hours: '7:30 AM - 10:00 PM',
    phone: '(608) 262-2263',
    website: 'https://union.wisc.edu/visit/der-rathskeller/',
  },
  {
    id: '5',
    name: 'State Street Brats',
    description: 'The legendary Madison sports bar known for red and white brats.',
    foodTypes: ['American', 'Pub Food', 'Sports Bar'],
    budget: 2,
    distance: 0.6,
    rating: 4.3,
    imageUrl: 'https://picsum.photos/seed/brats/800/600',
    address: '603 State St, Madison, WI 53703',
    hours: '11:00 AM - 2:00 AM',
    phone: '(608) 255-5544',
    website: 'https://statestreetbrats.com/',
  },
  {
    id: '6',
    name: 'Four Lakes Market',
    description: 'Dining hall in Dejope Residence Hall with great views of Lake Mendota.',
    foodTypes: ['American', 'Global', 'Salad Bar'],
    budget: 1,
    distance: 1.2,
    rating: 4.1,
    imageUrl: 'https://picsum.photos/seed/dejope/800/600',
    address: '640 Elm Dr, Madison, WI 53706',
    hours: '7:00 AM - 8:00 PM',
    phone: '(608) 262-1322',
    website: 'https://www.housing.wisc.edu/dining/four-lakes-market/',
  },
  {
    id: '7',
    name: "Dotty Dumpling's Dowry",
    description: 'Home of the world famous burgers and delicious homemade sauces.',
    foodTypes: ['Burgers', 'American'],
    budget: 2,
    distance: 0.8,
    rating: 4.7,
    imageUrl: 'https://picsum.photos/seed/dotty/800/600',
    address: '317 N Frances St, Madison, WI 53703',
    hours: '11:00 AM - 10:00 PM',
    phone: '(608) 259-0000',
    website: 'https://dottydumplingsdowry.com/',
  },
  {
    id: '8',
    name: 'Tavernakaya',
    description: 'Modern Japanese tavern serving sushi, ramen, and creative cocktails.',
    foodTypes: ['Japanese', 'Sushi', 'Ramen'],
    budget: 3,
    distance: 0.9,
    rating: 4.5,
    imageUrl: 'https://picsum.photos/seed/sushi/800/600',
    address: '27 E Main St, Madison, WI 53703',
    hours: '11:00 AM - 11:00 PM',
    phone: '(608) 555-0123',
    website: 'https://tavernakaya.com/',
  },
  {
    id: '9',
    name: "L'Etoile",
    description: 'Fine dining featuring locally sourced ingredients and an elegant atmosphere.',
    foodTypes: ['French', 'Fine Dining'],
    budget: 4,
    distance: 1.0,
    rating: 4.9,
    imageUrl: 'https://picsum.photos/seed/letoile/800/600',
    address: '1 S Pinckney St, Madison, WI 53703',
    hours: '5:00 PM - 10:00 PM',
    phone: '(608) 251-0500',
    website: 'https://letoile-restaurant.com/',
  },
  {
    id: '10',
    name: 'Mickies Dairy Bar',
    description: 'Classic 1950s-style diner famous for huge breakfasts and milkshakes.',
    foodTypes: ['Diner', 'Breakfast'],
    budget: 1,
    distance: 0.7,
    rating: 4.6,
    imageUrl: 'https://picsum.photos/seed/mickies/800/600',
    address: '1511 Monroe St, Madison, WI 53711',
    hours: '6:00 AM - 2:00 PM',
    phone: '(608) 256-9441',
    website: 'https://mickiesdairybar.com/',
  },
]
